resources:
  - h1c_h1c_passthrough.yaml
  - ingress.yaml
  - netty-backend.yaml
patches:
- path: deployment-patch.yaml
  target:
    group: apps
    version: v1
    kind: Deployment
    name: h1c-h1c-passthr-deployment
