[container.image]
repository = "ballerina"
name = "h2_h1c_passthrough"
base = "eclipse-temurin:11.0.15_10-jre-focal"

[[container.copy.files]]
sourceFile="./security/ballerinaKeystore.p12"
target="/home/ballerina/security/ballerinaKeystore.p12"

[cloud.deployment]
min_memory = "256Mi"
max_memory = "1024Mi"
min_cpu = "200m"
max_cpu="2000m"

[cloud.deployment.autoscaling]
min_replicas = 1
max_replicas = 1

[[cloud.secret.files]]
mount_dir="./security"
file="./security"
